"""
The Bestory Project

Add users

Revision ID: a9a77a287e02
Revises: f064bf12f0a1
Create Date: 2016-11-17 02:10:49.927800
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a9a77a287e02'
down_revision = 'f064bf12f0a1'
branch_labels = None
depends_on = None


def upgrade():
    """Auto generated by Alembic"""

    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_index(op.f('ix_users_username'), 'users', ['username'],
                    unique=False)

    op.add_column('stories',
                  sa.Column('author_id', sa.Integer(), nullable=False))

    op.create_index(op.f('ix_stories_author_id'), 'stories', ['author_id'],
                    unique=False)

    op.create_foreign_key(None, 'stories', 'users', ['author_id'], ['id'])

    op.add_column('topics',
                  sa.Column('slug', sa.String(length=32), nullable=False))


def downgrade():
    """Auto generated by Alembic"""

    op.drop_column('topics', 'slug')
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_index(op.f('ix_stories_author_id'), table_name='stories')
    op.drop_column('stories', 'author_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
