"""
The Bestory Project

initial

Revision ID: f064bf12f0a1
Revises: 
Create Date: 2016-11-12 20:40:05.961713
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f064bf12f0a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Auto generated by Alembic"""

    op.create_table('topics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=64), nullable=False),
                    sa.Column('desc', sa.Text(), nullable=False),
                    sa.Column('icon', sa.String(length=16), nullable=False),
                    sa.Column('stories_count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('stories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('topic_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('submit_date', sa.DateTime(timezone=True),
                              nullable=False),
                    sa.Column('edit_date', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.Column('publish_date', sa.DateTime(timezone=True),
                              nullable=True),
                    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_index(op.f('ix_stories_topic_id'), 'stories', ['topic_id'],
                    unique=False)


def downgrade():
    """Auto generated by Alembic"""

    op.drop_index(op.f('ix_stories_topic_id'), table_name='stories')
    op.drop_table('stories')
    op.drop_table('topics')
